Adding runpod-uploader command to start server
kodxana/RunPod-FilleUploader pull request #1
Opened 2024-02-20 22:07 UTC by justinwlin

Add something to start the runpod-uploader

2024-02-20 22:25 UTC, kodxana commented
I would not merge it with installation command

2024-02-20 22:39 UTC, kodxana requested changes
Separate how to run from installer command

2024-02-21 09:00 UTC, ashleykleynhans commented on README.md
> +#### Installation
Don't think this is needed because its already under the "How to Install section".

2024-02-21 09:00 UTC, ashleykleynhans commented on README.md
> +#### Starting server / application
I don't think this belongs under the "How to Install" section, should probably be in its own section.

2024-02-21 11:03 UTC, kodxana approved these changes

2024-02-21 11:03 UTC, merged